common_args:
  exp_config_name: "test_case_studies_exp_folk_pubcov_cs2_w_acc_0_75_w_fair_0_25"
  run_nums: [3]
  secrets_path: "/Users/denys_herasymuk/Research/NYU/VirnyFlow_Project/Code/virny-flow/virny_flow_demo/configs/secrets.env"

pipeline_args:
  dataset: "folk_pubcov"
  sensitive_attrs_for_intervention: ["RAC1P"]
  null_imputers: []
  fairness_interventions: []
  models: ["lr_clf", "rf_clf", "lgbm_clf"]
#  models: ["lr_clf", "rf_clf", "lgbm_clf", "gandalf_clf"]

optimisation_args:
  ref_point: [0.30, 0.10]
  objectives:
    - { name: "objective_1", metric: "F1", group: "overall", weight: 0.75 }
    - { name: "objective_2", metric: "Statistical_Parity_Difference", group: "RAC1P", weight: 0.25 }
  max_trials: 10
  num_workers: 8
  num_pp_candidates: 2
  training_set_fractions_for_halting: [0.7, 0.8, 0.9, 1.0]
  exploration_factor: 0.5
  risk_factor: 0.5

virny_args:
  bootstrap_fraction: 0.8
  n_estimators: 50
  sensitive_attributes_dct: {'SEX': '2', 'RAC1P': ['2', '3', '4', '5', '6', '7', '8', '9'], 'SEX&RAC1P': None}
