version: '3'

networks:
  task-manager-network:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - task-manager-network

  kafka_broker1:
    image: bitnami/kafka:latest
    container_name: kafka_broker1
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - task-manager-network

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    networks:
      - task-manager-network
    depends_on:
      - kafka_broker1
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka_broker1:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka_broker1:9092 --create --if-not-exists --topic NewTasksQueue --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka_broker1:9092 --create --if-not-exists --topic CompletedTasksQueue --replication-factor 1 --partitions 1
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka_broker1:9092 --list
      "
