exp_config_name: "german_experiments2"
dataset: "german"
sensitive_attrs_for_intervention: ["sex"]
null_imputers: ["median-mode", "median-dummy"]
fairness_interventions: ["DIR"]
#models: ["lr_clf", "rf_clf"]
models: ["lr_clf"]
random_state: 42
secrets_path: "/Users/denys_herasymuk/Research/NYU/VirnyFlow_Project/Code/virny-flow/virny_flow_demo/configs/secrets.env"
#secrets_path: "./configs/secrets.env"
#secrets_path: "./virny_flow_demo/configs/secrets.env"